app:
    resource: "@AppBundle/Controller/"
    type:     annotation

acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   /

acme_cristi:
    path: /Studenti/BaciuWahlCristian
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    CristiBaciu.html.twig

acme_iulian:
    path: studenti/iulian
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    iulian.html.twig

acme_delia:
    path: /studenti/DeliaGiurgiu
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    DeliaGiurgiu.html.twig

acme_george:
    path: studenti/PodaruGeorge
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    PodaruGeorge.html.twig
<<<<<<< HEAD
cucui_alina:
    path: studenti/AlinaCucui
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    AlinaCucui.html.twig
=======

floreamihaela:
    path: studenti/floreamihaela
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    floreamihaela.html.twig
>>>>>>> 433b6f1753494a8f4dfa4565cb8256e0c9b2b180
